-- Create test users with simple password hash
USE `e-mading`;

-- Clear existing users
DELETE FROM users;

-- Insert users with password 'password' (hash generated by PHP password_hash)
INSERT INTO `users` (`id_user`, `nama`, `username`, `password`, `role`, `created_at`, `updated_at`) VALUES
(1, 'Admin', 'admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', NOW(), NOW()),
(2, 'Pak Guru', 'guru', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'guru', NOW(), NOW()),
(3, 'Ahmad Siswa', 'siswa', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'siswa', NOW(), NOW());

-- Verify users created
SELECT id_user, nama, username, role FROM users;